name: metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
    - name: Fortune
      uses: lowlighter/metrics@main
      with:
        filename: fortune.svg
        token: NOT_NEEDED
        base: ""
        plugin_fortune: yes
    - name: Midly interesting facts
      uses: lowlighter/metrics@latest
      with:
        filename: facts.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: no
        plugin_habits_days: 30
        config_timezone: Australia/Sydney
